return {
  imaps = {
    leader = "'",
    enable = {
      { lhs = '0', rhs = [[\emptyset]] },
      { lhs = '6', rhs = [[\partial]] },
      { lhs = '8', rhs = [[\infty]] },
      { lhs = '=', rhs = [[\equiv]] },
      { lhs = '\\', rhs = [[\setminus]] },
      { lhs = '.', rhs = [[\cdot]] },
      { lhs = '*', rhs = [[\times]] },
      { lhs = '<', rhs = [[\langle]] },
      { lhs = '>', rhs = [[\rangle]] },
      { lhs = 'H', rhs = [[\hbar]] },
      { lhs = '+', rhs = [[\dagger]] },
      { lhs = '[', rhs = [[\subseteq]] },
      { lhs = ']', rhs = [[\supseteq]] },
      { lhs = '^', rhs = [[\hat]] },
      { lhs = '~', rhs = [[\tilde]] },
      { lhs = '(', rhs = [[\subset]] },
      { lhs = ')', rhs = [[\supset]] },
      { lhs = 'A', rhs = [[\forall]] },
      { lhs = 'D', rhs = [[\Delta]] },
      { lhs = 'E', rhs = [[\exists]] },
      { lhs = 'F', rhs = [[\Phi]] },
      { lhs = 'G', rhs = [[\Gamma]] },
      { lhs = 'L', rhs = [[\Lambda]] },
      { lhs = 'P', rhs = [[\Pi]] },
      { lhs = 'Q', rhs = [[\Theta]] },
      { lhs = 'S', rhs = [[\Sigma]] },
      { lhs = 'U', rhs = [[\Upsilon]] },
      { lhs = 'W', rhs = [[\Omega]] },
      { lhs = 'X', rhs = [[\Xi]] },
      { lhs = 'Y', rhs = [[\Psi]] },
      { lhs = 'a', rhs = [[\alpha]] },
      { lhs = 'b', rhs = [[\beta]] },
      { lhs = 'c', rhs = [[\chi]] },
      { lhs = 'd', rhs = [[\delta]] },
      { lhs = 'e', rhs = [[\epsilon]] },
      { lhs = 'f', rhs = [[\phi]] },
      { lhs = 'g', rhs = [[\gamma]] },
      { lhs = 'h', rhs = [[\eta]] },
      { lhs = 'i', rhs = [[\iota]] },
      { lhs = 'jH', rhs = [[\Leftarrow]] },
      { lhs = 'jJ', rhs = [[\Downarrow]] },
      { lhs = 'jK', rhs = [[\Uparrow]] },
      { lhs = 'jL', rhs = [[\Rightarrow]] },
      { lhs = 'jh', rhs = [[\leftarrow]] },
      { lhs = 'jj', rhs = [[\downarrow]] },
      { lhs = 'jk', rhs = [[\uparrow]] },
      { lhs = 'jl', rhs = [[\rightarrow]] },
      { lhs = 'k', rhs = [[\kappa]] },
      { lhs = 'l', rhs = [[\lambda]] },
      { lhs = 'm', rhs = [[\mu]] },
      { lhs = 'n', rhs = [[\nu]] },
      { lhs = 'p', rhs = [[\pi]] },
      { lhs = 'q', rhs = [[\theta]] },
      { lhs = 'r', rhs = [[\rho]] },
      { lhs = 's', rhs = [[\sigma]] },
      { lhs = 't', rhs = [[\tau]] },
      { lhs = 'u', rhs = [[\upsilon]] },
      { lhs = 've', rhs = [[\varepsilon]] },
      { lhs = 'vf', rhs = [[\varphi]] },
      { lhs = 'vk', rhs = [[\varkappa]] },
      { lhs = 'vq', rhs = [[\vartheta]] },
      { lhs = 'vr', rhs = [[\varrho]] },
      { lhs = 'vs', rhs = [[\varsigma]] },
      { lhs = 'w', rhs = [[\omega]] },
      { lhs = 'x', rhs = [[\xi]] },
      { lhs = 'y', rhs = [[\psi]] },
      { lhs = 'z', rhs = [[\zeta]] },
    },
    disable = {},
    select_mode = true,
  },
  use_default = true,
  highlights = {
    texmapSurrounds = { link = 'Search' },
  },
}
